### ISSUE TITLE
output-directory not recognized in config

### ISSUE THREAD

**Issue by balazsdukai** [3DBAG/roofer#62]
I have a config file:

```toml
    polygon-source = "PG:dbname=baseregisters_test user=baseregisters_test_user port=5432 host=data-postgresql password=baseregisters_test_pswd sslmode=allow tables=reconstruction_input.t_3/8/4"
    id-attribute = "identificatie"
    force-lod11-attribute = "kas_warenhuis"
    
    [[pointclouds]]
    name = "AHN3"
    quality = 1
    source = ['/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960606.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960607.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960608.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960609.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961935.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961936.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961937.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961938.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961939.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961940.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963265.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963266.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963267.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963268.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963269.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963270.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964596.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964597.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964598.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964599.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964600.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965925.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965926.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965927.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965928.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965929.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965930.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967255.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967256.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967258.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967259.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967260.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968585.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968586.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968588.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968589.laz']
    
    [[pointclouds]]
    name = "AHN4"
    quality = 0
    source = ['/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960606.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960607.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960608.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960609.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961935.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961936.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961937.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961938.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961939.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961940.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963265.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963266.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963267.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963268.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963269.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963270.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964596.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964597.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964598.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964599.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964600.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965925.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965926.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965927.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965928.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965929.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965930.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967255.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967256.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967258.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967259.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967260.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968585.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968586.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968588.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968589.laz']
    
    cellsize = 0.5
    lod = 22
    
    split-cjseq = false
    output-directory = "/data/volume/release_develop/3DBAG/crop_reconstruct/3/8/4"
```

Running roofer as: `roofer --config roofer.toml`

I get an error:

`[2024-11-06 14:08:27.560] [stderr] [error] Failed to parse command line arguments. Unable set all inputs and output. Need to provide at least <ouput path> and set input paths in config file or provide all of <point cloud sources> <polygon source> <ouput path>. Use '-h' to print usage information.`

As far as I can tell,  <point cloud sources> <polygon source> <ouput path> are all set in the config file.

**Comment by Ylannl** [comment]
The problem here is that the properties on the bottom (including the output-directory) are read as being part of the last declare `[[pointcloud]]` table, instead of being read as root level properties. This can be a bit confusing about TOML, I will add an error message specifically about this. 

In any case just moving those properties on the bottom to the top section of the file should work:
```toml
    polygon-source = "PG:dbname=baseregisters_test user=baseregisters_test_user port=5432 host=data-postgresql password=baseregisters_test_pswd sslmode=allow tables=reconstruction_input.t_3/8/4"
    id-attribute = "identificatie"
    force-lod11-attribute = "kas_warenhuis"

    cellsize = 0.5
    lod = 22
    
    split-cjseq = false
    output-directory = "/data/volume/release_develop/3DBAG/crop_reconstruct/3/8/4"
    
    [[pointclouds]]
    name = "AHN3"
    quality = 1
    source = ['/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960606.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960607.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960608.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_960609.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961935.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961936.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961937.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961938.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961939.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_961940.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963265.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963266.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963267.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963268.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963269.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_963270.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964596.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964597.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964598.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964599.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_964600.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965925.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965926.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965927.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965928.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965929.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_965930.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967255.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967256.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967258.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967259.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_967260.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968585.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968586.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968588.laz', '/data/volume/release_develop/pointcloud/AHN3/tiles_200m/t_968589.laz']
    
    [[pointclouds]]
    name = "AHN4"
    quality = 0
    source = ['/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960606.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960607.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960608.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_960609.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961935.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961936.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961937.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961938.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961939.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_961940.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963265.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963266.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963267.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963268.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963269.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_963270.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964596.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964597.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964598.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964599.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_964600.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965925.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965926.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965927.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965928.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965929.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_965930.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967255.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967256.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967258.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967259.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_967260.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968585.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968586.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968588.laz', '/data/volume/release_develop/pointcloud/AHN4/tiles_200m/t_968589.laz']
```
